package(
    default_applicable_licenses = ["//vmsdk:license"],
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "valkey_module",
    hdrs = [
        "valkey_module.h",
    ],
)
