name: Integration tests

on:
  pull_request: # This triggers the workflow for pull requests
    branches:
      - main    # Run tests for pull requests targeting the "main" branch
  push:
    branches:
      - main    # Optional: Run tests for direct pushes to "main"
  workflow_dispatch: # allow manual triggering

concurrency:
  group: integration-tests-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Docker to build and run the container
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Build the Docker image from the Dockerfile in your repo
    - name: Build Docker Image
      run: docker build -t presubmit-image -f .devcontainer/Dockerfile .

    - name: Run Integration Tests
      run: docker run --privileged --rm  -v "$(pwd):/workspace" --user "ubuntu:ubuntu" presubmit-image sudo ci/build_ubuntu.sh --run-integration-tests --retries=3
