name: unittests-macos

on:
  pull_request:
  push:
  workflow_dispatch:

concurrency:
  group: unittests-macos-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  cmake-tests-macos:
    runs-on: macos-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Verify Branch
      env:
        BRANCH: ${{ github.base_ref || github.ref_name }}
      run: grep -qxF "$BRANCH" .github/release-branches.txt

    # Set up Docker to build and run the container
    - name: Build Code
      run: ./build.sh
