name: unittests-macos

on:
  pull_request:
    branches:
      - main
      - "[0-9].[0-9]"
    paths-ignore:
      - '**/*.md'
      - '**/00-RELEASENOTES'
  push:
    branches:
      - main
      - "[0-9].[0-9]"
    paths-ignore:
      - '**/*.md'
      - '**/00-RELEASENOTES'
  workflow_dispatch:

concurrency:
  group: unittests-macos-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  cmake-tests-macos:
    runs-on: macos-latest

    steps:
    # Checkout the code from the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Docker to build and run the container
    - name: Build Code
      run: ./build.sh
